const ACTION_TYPE = {
  GET_MESSAGES_ACTION: 'GET_MESSAGES_ACTION',
  GET_MESSAGES_REQUEST: 'GET_MESSAGES_REQUEST',
  GET_MESSAGES_REQUEST_SUCCESS: 'GET_MESSAGES_REQUEST_SUCCESS',
  GET_MESSAGES_REQUEST_FAIL: 'GET_MESSAGES_REQUEST_FAIL',

  NEW_MESSAGE_ACTION: 'NEW_MESSAGE_ACTION',
  NEW_MESSAGE_RESPONSE_SUCCESS: 'NEW_MESSAGE_RESPONSE_SUCCESS',
  NEW_MESSAGE_RESPONSE_FAIL: 'NEW_MESSAGE_RESPONSE_FAIL',
};

export default ACTION_TYPE;
